### PR TITLE
Reset Context properly

### PR DESCRIPTION
**Pull request by fyrchik**

### CODE REVIEW

**Comment by roman-khimov** [comment]
It'd be nice to add more explanations to the commit message and mention #18.

**Comment by roman-khimov** [comment]
Still fails to recover
[four.log](https://github.com/nspcc-dev/dbft/files/4138606/four.log)
[one.log](https://github.com/nspcc-dev/dbft/files/4138607/one.log)
[three.log](https://github.com/nspcc-dev/dbft/files/4138608/three.log)
[two.log](https://github.com/nspcc-dev/dbft/files/4138609/two.log)

**Comment by roman-khimov** [comment]
Produced the block 6014!
[four.log](https://github.com/nspcc-dev/dbft/files/4138681/four.log)
[one.log](https://github.com/nspcc-dev/dbft/files/4138682/one.log)
[three.log](https://github.com/nspcc-dev/dbft/files/4138683/three.log)
[two.log](https://github.com/nspcc-dev/dbft/files/4138684/two.log)

**Comment by fyrchik** [comment]
Closes #15 , #18 , #17 .

**Pull request merged**
